### ISSUE TITLE
Changing Twitch Streamer Name in OSRS Streamers

### ISSUE THREAD

**Issue by elisattv** [rhoiyds/osrs-streamers#18]
Hi! I recently changed my name from Elfyosrs to Elisa on Twitch. Can you please change it so that my rsn's Mystic Elfy and Elfyisthicc are no longer under twitch.tv/elfyosrs, but rather twitch.tv/elisa? If you need any video proof it's on my channel. Thanks!

**Comment by WesleyM77** [comment]
Hey there, I just became a maintainer of this plugin. I'm going through the backlog of requests and should get yours processed today. I'll close this ticket when I've submitted to plugin-hub. Thanks for being so patient! We also have "Wild Elfy" linked to your twitch, does that account still belong to you? I only ask since that isn't listed in your above request.

**Comment by elisattv** [comment]
Hi Wesley,

Wild Elfy and Mystic Elfy are my accounts. My twitch is twitch.tv/Elisa. I
changed from twitch.tv/elfyosrs. Let me know when it's updated thanks!! :)

Elisa

**Comment by WesleyM77** [comment]
Already handled, I was just asking about the third account which is still linked. I updated your linked twitch name. Should be good to go!
