### ISSUE TITLE
Feature request: Option to only show overlay if streamer is live

### ISSUE THREAD

**Issue by ShaunDreclin** [rhoiyds/osrs-streamers#2]

**Comment by royporter7** [comment]
Great suggestion. Before I consider this can you clarify a few things? I assume you’re suggesting this because you’ve come across too many streamers who aren’t even live?
Additionally, are you aware that the plugin already differentiates live (purple) streamers from non-live (grey) streamers?

**Comment by ShaunDreclin** [comment]
Yeah I've run into several today and its sorta irrelevant to me that they are a streamer if they're not currently streaming haha

**Comment by royporter7** [comment]
Yep, makes sense to me. I’ll implement this soon and include it with the next plugin update.
You didn’t answer my other question, but don’t forget to copy and paste your token from the below link into your plugin settings; otherwise the plugin cannot check if streamers are live or not.
https://rhoiyds.github.io/osrs-streamers/

**Comment by ShaunDreclin** [comment]
Yea I've got that part working

**Comment by royporter7** [comment]
Legend.
Stay tuned for the update in a few days - I’ll comment here when it’s live.

**Comment by royporter7** [comment]
This update should now be live. Thanks for an excellent suggestion. Please feel free to comment again with any requests/issues in the future.
