### ISSUE TITLE
Right Click Option for specific streamer

### ISSUE THREAD

**Issue by BayleeYo** [rhoiyds/osrs-streamers#7]
https://www.twitch.tv/kittyjuicertv

Streamer: KittyjuicerTV

When I right click on player and click twitch in menu. It takes me to https://www.twitch.tv/null

When I search streamer in the plugin sidebar. It takes me to the correct URL listed at top of this issue. 

PS> Yall rock for this plugin :D

**Comment by BayleeYo** [comment]
Just found another player on the list
https://www.twitch.tv/xilLuZioNisTx
67 Gtos Rule

They also are pulling up Null when clicking twitch in game. This player/streamer was not currently streaming. The player above (Kitty) was live.

Could this be for everyone?

**Comment by royporter7** [comment]
You're absolutely right. Working on this right away - I have a hunch for what the problem may be.

**Comment by BayleeYo** [comment]
Awesome! I appreciate you working hard and taking care of it!

**Comment by royporter7** [comment]
The issue is fixed, tested and working. (RuneLite devs will review it and the update should go live in no more than 12 hours or so from now)
To summarize: the issue was that players with spaces in their names actually don't have 'spaces' in Jagex's code, they have a NBSP instead (almost like a 'tab' character).
The plugin was trying to find a streamer 'John(space)Smith', but according to Jagex it's actually 'John(nbsp)Smith'. (Hence NULL)
Thanks again for being an absolute legend and reporting this issue.
If you ever find anything wrong, or have any feature suggestions please have no hesitations in coming here and logging them! :)
